version: '3'

services:

  mongo:
    image: mongo
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: password
    networks:
      - app-tier
    ports:
      - "27027:27017"
  app:
    build: .
    image: fastapi_mongo
    container_name: fastapi_mongo
    env_file: .env
    ports:
      - "8080:5011"
networks:
  app-tier:
    driver: bridge
